include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "lib/generated_plugin_registrant.dart"
  
  errors:
    # ignore 주석 처리한 deprecated_member_use 에러 무시
    deprecated_member_use: ignore

linter:
  rules:
    # new - 추가된 규칙
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true
    use_key_in_widget_constructors: true